all:
	g++ -O2 -I /work/KellerLab/opt/bin/include ./src/IBG-ProjectFISHR-B.cpp ./src/HandleFlags.cpp ./src/ReadFiles.cpp ./src/Compute.cpp ./src/Ibd.cpp ./src/Bmid.cpp ./src/Ped.cpp -o IBG-ProjectFISHR-B
